### ISSUE TITLE
Compile Guards

### ISSUE THREAD

**Issue by RedSkittleFox** [Ubpa/USmallFlat#1]
Missing `#ifndef` `#define` `#endif` compile guard and `#pragma once` defined twice.

**Comment by Ubpa** [comment]
Because of network problems, I hasn't committed some important changes. I will update codes tomorrow.
Thanks!

**Comment by Ubpa** [comment]
I don't like `#ifndef`-`#define`-`#endif` compile guard. I update codes  now.
[0.1.0](https://github.com/Ubpa/USmallVector/tree/0.1.0)

**Comment by RedSkittleFox** [comment]
`#pragma once` is not part of the standard which means your code might not compile on some platforms.

**Comment by Ubpa** [comment]
I use C++20, and I think that every modern compiler will support `#pragma once` if it supports C++20.
Because the implementation of C++20 is far more complicated than the implementation of `#pragma once`. I don't believe that such a compiler will exist. If you know any above-mentioned complier, please tell me. Otherwise, I don't want to write ugly codes for a nonexistent compiler.
